### ISSUE TITLE
RuntimeError: The size of tensor a (33) must match the size of tensor b (32) at non-singleton dimension 1

### ISSUE THREAD

**Issue by Ultraman-Orb** [silverriver/Stylized_Dialog#1]
RuntimeError: The size of tensor a (33) must match the size of tensor b (32) at non-singleton dimension 1
dialog batchsize 2   text batchsize 4时，是哪个地方的维度出现了问题？
![屏幕截图 2020-12-27 155424](https://user-images.githubusercontent.com/56676402/103166334-f84dbc80-485b-11eb-8ad5-b4d262bfd35b.png)

**Comment by acst1223** [comment]
我按照你的配置dialog batchsize 2 text batchsize 4 跑了，并没有遇到你说的问题。你config里其他的地方修改了吗？用的是什么pytorch版本？

**Comment by acst1223** [comment]
并且我也检查了x_embed的维数，第一维的长度都是16，所以相加没有任何问题

**Comment by acst1223** [comment]
并且我也检查了x_embed的维数，第一维的长度都是16，所以相加没有任何问题。你可否调试一下检查一下相关的shape情况？

**Comment by Ultraman-Orb** [comment]
> 并且我也检查了x_embed的维数，第一维的长度都是16，所以相加没有任何问题。你可否调试一下检查一下相关的shape情况？

首先非常感谢您在半夜的时候还能调试解答。配置文件加了一个就是max_resp_len:50(之前报错提示显示没有这个参数)，我用的pytorch是1.7，因为1.4的是cuda10版本，调用gpu实在是太慢了，最后那个维度的问题不是在最开始的报错，而是在999个step之后（999/150000或者1000/30000）才出现这个错误，不知道您是否跑完一个epoch之后还没出现问题
![屏幕截图 2020-12-28 100659](https://user-images.githubusercontent.com/56676402/103184791-942b0700-48f4-11eb-9630-9196b3e385e3.png)
![屏幕截图 2020-12-28 100744](https://user-images.githubusercontent.com/56676402/103184799-9a20e800-48f4-11eb-997e-e562fa5096ec.png)

**Comment by silverriver** [comment]
@Ultraman-Orb 你好，我更新了一下WDJN项目下的config.json文件，添加上了max_resp_len字段。

从您的反馈来看，应该是在inverse dialogue model中采样数据的部分出的问题，这部分代码只有在训练step超过config文件中的“bt_freeze_step”后才会被调用。我猜您所使用的config文件中bt_freeze_step=500， batch_split=2，所以才会在第500 * 2个step左右报错。

但是根据我重现的结果，从inverse dialogue model中采样的部分并没有问题。并且我将 https://github.com/silverriver/Stylized_Dialog/blob/main/WDJN/bt_beam/config.json 文件中的"text_batch_size"字段设置为了5，“bt_freeze_step”字段设置为了10，使用4块GPU并行跑完了1个epoch，并没有报错。

我测试的pytorch版本是1.7.1 + cuda 10.1

您能否提供一下这一问题的完整重现路径。

**Comment by Ultraman-Orb** [comment]
> @Ultraman-Orb 你好，我更新了一下WDJN项目下的config.json文件，添加上了max_resp_len字段。
> 
> 从您的反馈来看，应该是在inverse dialogue model中采样数据的部分出的问题，这部分代码只有在训练step超过config文件中的“bt_freeze_step”后才会被调用。我猜您所使用的config文件中bt_freeze_step=500， batch_split=2，所以才会在第500 * 2个step左右报错。
> 
> 但是根据我重现的结果，从inverse dialogue model中采样的部分并没有问题。并且我将 https://github.com/silverriver/Stylized_Dialog/blob/main/WDJN/bt_beam/config.json 文件中的"text_batch_size"字段设置为了5，“bt_freeze_step”字段设置为了10，使用4块GPU并行跑完了1个epoch，并没有报错。
> 
> 我测试的pytorch版本是1.7.1 + cuda 10.1
> 
> 您能否提供一下这一问题的完整重现路径。

非常感谢您的解答，您的判断非常准，确实是bt_freeze_step=500， batch_split=2，但是非常抱歉，我不明白您说的完整重现路径是什么意思，是加载的语料路径，还是那个超参数配置文件，我的语料路径由于总是报错，我就改成绝对路径了。

**Comment by silverriver** [comment]
就是如何重现这个问题？

您可以提供一下您的具体操作步骤么？

**Comment by Ultraman-Orb** [comment]
> 就是如何重现这个问题？
> 
> 您可以提供一下您的具体操作步骤么？

![屏幕截图 2020-12-28 151500](https://user-images.githubusercontent.com/56676402/103196704-9e162f80-491f-11eb-80b1-2ff72683feab.png)
![屏幕截图 2020-12-28 151700](https://user-images.githubusercontent.com/56676402/103196840-e2093480-491f-11eb-978b-4e0632b9980c.png)
![屏幕截图 2020-12-28 152514](https://user-images.githubusercontent.com/56676402/103197398-e97d0d80-4920-11eb-8390-ed1cf3ec7073.png)
其他的地方我都没变，我只有一块8G的gpu所以就没执行sh文件（第一张图，在控制台输入），改完bt_freeze_step=10， batch_split=2之后在434/100000的时候又报了这个错误

**Comment by Ultraman-Orb** [comment]
> > 就是如何重现这个问题？
> > 您可以提供一下您的具体操作步骤么？
> 

"vocab_path": "D:/python/Stylized_Dialog-main/data/chinese_gpt_original/dict.txt",
  "max_seq_len": 50,
  "beam_size": 4,
  "top_p_top_k_sample_size": 5,
  "diversity_coef": 0,
  "diversity_groups": 2,
  "sample": false,
  "annealing_topk": 20,
  "annealing_topp": 0.9,
  "temperature": 0.8,
  "annealing": 0,
  "length_penalty": 2.2,
  "n_layers": 12,
  "n_pos_embeddings": 512,
  "embeddings_size": 768,
  "n_heads": 12,
  "dropout": 0.1,
  "embed_dropout": 0.1,
  "attn_dropout": 0.1,
  "ff_dropout": 0.1,
  "eval_steps": 200,
  "save_interval": 1000,
  "max_resp_len": 26,
  "comment": "below is the training parameters",
  "n_epochs": 500,
  "dialog_batch_size": 3,
  "text_batch_size": 5,
  "batch_split": 2,
  "lr": 6.25e-5,
  "lr_warmup": 1000,
  "n_jobs": 0,
  "label_smoothing": 0.1,
  "clip_grad": 1.0,
  "seed": 42,
  "load_last": false,
  "n_styles": 2,
  "anneal_constant": 2000,
  "bt_weight": 0.5,
  "bt_freeze_step": 10,

  "train_dialogue_data": "D:/python/Stylized_Dialog-main/data/chinese_gpt_original/crowded_300K.txt",
  "train_text_data": "D:/python/Stylized_Dialog-main/data/chinese_gpt_original/jinyong_dialogue_text_style.txt",
  "valid_dialogue_data": ["D:/python/Stylized_Dialog-main/data/chinese_gpt_original/valid_2k.txt", "D:/python/Stylized_Dialog-main/data/chinese_gpt_original/jinyong_2k_eval.txt"],

  "train_dir": "train",
  "eval_dir": "eval",
  "data_dir": "data",
  "log_dir": "log",
  "best_dir": "best",

  "cgpt_parameters_dir": "D:/python/Stylized_Dialog-main/data/chinese_gpt_original/Cgpt_model.bin
这是我的配置文件，使用的是python 3.7.4

**Comment by silverriver** [comment]
你好，我使用你的配置文件，使用一个GPU，跑了一个epoch，并没有发现您说的问题。
环境是python 3.7.9, pytorch 1.7.1 + cuda 10.1 + Ubuntu 16.04.5

`python3 Stylized_Dialog/WDJN/bt_beam/train.py --config data/Stylized_Dialog/config.json --gpu 0`

  "max_seq_len": 50,
  "max_resp_len": 26,
  "beam_size": 4,
  "top_p_top_k_sample_size": 5,
  "diversity_coef": 0,
  "diversity_groups": 4,
  "sample": false,
  "annealing_topk": 20,
  "annealing_topp": 0.9,
  "temperature": 0.8,
  "annealing": 0,
  "length_penalty": 2.2,
  "n_layers": 12,
  "n_pos_embeddings": 512,
  "embeddings_size": 768,
  "n_heads": 12,
  "dropout": 0.1,
  "embed_dropout": 0.1,
  "attn_dropout": 0.1,
  "ff_dropout": 0.1,
  "eval_steps": 300,
  "save_interval": 1000,

  "comment": "below is the training parameters",
  "n_epochs": 500,
  "dialog_batch_size": 30,
  "text_batch_size": 5,
  "batch_split": 2,
  "lr": 8.25e-5,
  "lr_warmup": 1000,
  "n_jobs": 0,
  "label_smoothing": 0.1,
  "clip_grad": 1.0,
  "seed": 42,
  "load_last": false,
  "n_styles": 2,
  "anneal_constant": 2000,
  "bt_weight": 0.5,
  "bt_freeze_step": 10,

能否麻烦您再次核对代码是否有修改，如果问题依然存在，麻烦您将运行出错的代码+数据+详细运行指令分享给我 （发邮件或上传至您自己的repo均可）。

**Comment by Ultraman-Orb** [comment]
> 你好，我使用你的配置文件，使用一个GPU，跑了一个epoch，并没有发现您说的问题。
> 环境是python 3.7.9, pytorch 1.7.1 + cuda 10.1 + Ubuntu 16.04.5
> 
> `python3 Stylized_Dialog/WDJN/bt_beam/train.py --config data/Stylized_Dialog/config.json --gpu 0`
> 
> "max_seq_len": 50,
> "max_resp_len": 26,
> "beam_size": 4,
> "top_p_top_k_sample_size": 5,
> "diversity_coef": 0,
> "diversity_groups": 4,
> "sample": false,
> "annealing_topk": 20,
> "annealing_topp": 0.9,
> "temperature": 0.8,
> "annealing": 0,
> "length_penalty": 2.2,
> "n_layers": 12,
> "n_pos_embeddings": 512,
> "embeddings_size": 768,
> "n_heads": 12,
> "dropout": 0.1,
> "embed_dropout": 0.1,
> "attn_dropout": 0.1,
> "ff_dropout": 0.1,
> "eval_steps": 300,
> "save_interval": 1000,
> 
> "comment": "below is the training parameters",
> "n_epochs": 500,
> "dialog_batch_size": 30,
> "text_batch_size": 5,
> "batch_split": 2,
> "lr": 8.25e-5,
> "lr_warmup": 1000,
> "n_jobs": 0,
> "label_smoothing": 0.1,
> "clip_grad": 1.0,
> "seed": 42,
> "load_last": false,
> "n_styles": 2,
> "anneal_constant": 2000,
> "bt_weight": 0.5,
> "bt_freeze_step": 10,
> 
> 能否麻烦您再次核对代码是否有修改，如果问题依然存在，麻烦您将运行出错的代码+数据+详细运行指令分享给我 （发邮件或上传至您自己的repo均可）。

根据您的配置文件，我换成了eval_steps": 300和"diversity_groups": 4,之后现在跑到1511/100000而且一直在继续训练，代码部分我只改了这个部分
if "out of memory" in str(e):
            print("WARNING: out of memory")
            if hasattr(torch.cuda,'empty_chache'):
                torch.cuda.empty_cache()
        else:
            torch.save(trainer.state_dict(), os.path.join(train_dir, 'interrupt.pt'))
        raise e

**Comment by acst1223** [comment]
您好，我们已经复现出了这个bug。大致判断来说是
fp_s1, fp_s1_len = self.model_fp.beam_search_train_bt(enc_text, dec_id=torch.zeros_like(text_style_id))
这一行的beam_search_train_bt函数存在一些问题。我们会尽快解决这个问题。

**Comment by Ultraman-Orb** [comment]
> 您好，我们已经复现出了这个bug。大致判断来说是
> fp_s1, fp_s1_len = self.model_fp.beam_search_train_bt(enc_text, dec_id=torch.zeros_like(text_style_id))
> 这一行的beam_search_train_bt函数存在一些问题。我们会尽快解决这个问题。

真的是非常感谢，还想请问一下，解决之后在哪能看到解决后的版本

**Comment by Ultraman-Orb** [comment]
> 你好，我使用你的配置文件，使用一个GPU，跑了一个epoch，并没有发现您说的问题。
> 环境是python 3.7.9, pytorch 1.7.1 + cuda 10.1 + Ubuntu 16.04.5
> 
> `python3 Stylized_Dialog/WDJN/bt_beam/train.py --config data/Stylized_Dialog/config.json --gpu 0`
> 
> "max_seq_len": 50,
> "max_resp_len": 26,
> "beam_size": 4,
> "top_p_top_k_sample_size": 5,
> "diversity_coef": 0,
> "diversity_groups": 4,
> "sample": false,
> "annealing_topk": 20,
> "annealing_topp": 0.9,
> "temperature": 0.8,
> "annealing": 0,
> "length_penalty": 2.2,
> "n_layers": 12,
> "n_pos_embeddings": 512,
> "embeddings_size": 768,
> "n_heads": 12,
> "dropout": 0.1,
> "embed_dropout": 0.1,
> "attn_dropout": 0.1,
> "ff_dropout": 0.1,
> "eval_steps": 300,
> "save_interval": 1000,
> 
> "comment": "below is the training parameters",
> "n_epochs": 500,
> "dialog_batch_size": 30,
> "text_batch_size": 5,
> "batch_split": 2,
> "lr": 8.25e-5,
> "lr_warmup": 1000,
> "n_jobs": 0,
> "label_smoothing": 0.1,
> "clip_grad": 1.0,
> "seed": 42,
> "load_last": false,
> "n_styles": 2,
> "anneal_constant": 2000,
> "bt_weight": 0.5,
> "bt_freeze_step": 10,
> 
> 能否麻烦您再次核对代码是否有修改，如果问题依然存在，麻烦您将运行出错的代码+数据+详细运行指令分享给我 （发邮件或上传至您自己的repo均可）。

非常感谢您能按照我的环境去调试解答。

**Comment by acst1223** [comment]
> 真的是非常感谢，还想请问一下，解决之后在哪能看到解决后的版本

我们解决之后会commit的，你重新pull或者clone一下就能看到了

**Comment by acst1223** [comment]
代码已经更新。你可以检查一下问题解决了没有。

**Comment by Ultraman-Orb** [comment]
> 代码已经更新。你可以检查一下问题解决了没有。

好的，非常感谢，正在调试

**Comment by Ultraman-Orb** [comment]
> 代码已经更新。你可以检查一下问题解决了没有。

目前，更新后的没有出现问题，但是还有一个问题想咨询一下，原始的那个项目配置文件改成eval_steps": 300和"diversity_groups": 4之后就没出现bug，不知道是什么原因？

**Comment by acst1223** [comment]
首先，从bug出现的原因来看，之前的代码中，diversity_groups==beam_size的时候确实可以规避这个bug。
其次，这个bug是模型在做反向infer的时候出现的。由于infer过程是一个概率过程，这个bug也是概率出现的。我自己跑了几十次实验，即使完全按照你的配置，也有相当多的实验没有出现这个bug。
目前从原理上这个bug已经不可能再出现了。也感谢您的反馈。

**Comment by acst1223** [comment]
如果您没有问题这个issue就close了
