### ISSUE TITLE
How long does it take to run the code?

### ISSUE THREAD

**Issue by jin8** [silverriver/Stylized_Dialog#2]
How long does it take to train on TCFC dataset? Could you tell the experiment setting (GPU)?
I wasn't able to find Appendix file for the paper (https://ojs.aaai.org/index.php/AAAI/article/view/17711).

**Comment by silverriver** [comment]
We use 4 Quadro RTX 6000 GPU with 24G memory.
The training tasks about 10 hours if I remember correctly.

**Comment by silverriver** [comment]
I have uploaded a camera ready version of our paper and appendix in this repo.

**Comment by jin8** [comment]
Thank you for your prompt response:)
